export const ROUTES = {
  LOGIN: "/login",
  SETUP: "/setup",
  DASHBOARD: "/dashboard",
  CLIENTS: "/clients",
  AI_MODELS: "/ai-models",
  OPENROUTER_CALLBACK: "/ai-models/openrouter/callback",
  SESSIONS: "/sessions",
  SESSION_DETAIL: (id: string) => `/sessions/${id}`,
  CONTEXTS: "/contexts",
  TASKS: "/tasks",
  APPS: "/apps",
  GOOGLE_CALLBACK: "/apps/google/callback",
  CONTENT: "/content",
  MEDIA: "/media",
} as const

export const API = {
  AUTH: {
    SETUP: "auth/setup",
    SIGN_IN: "auth/sign-in",
    SIGN_UP: "auth/sign-up",
    ME: "auth/me",
  },
  CLIENT: {
    LIST: "client",
    DETAIL: (id: string) => `client/${id}`,
    SET_MODEL: (id: string) => `client/${id}/model`,
    SET_ENTITY_MODE: (id: string) => `client/${id}/entity-mode`,
    CREDENTIAL: (id: string) => `client/${id}/credential`,
    CREDENTIAL_ITEM: (id: string, credId: string) => `client/${id}/credential/${credId}`,
  },
  MASTER: {
    CLIENT_TYPES: "master/client-types",
    AI_MODELS: "master/ai-models",
  },
  AI_MODEL: {
    LIST: "ai-model",
    DETAIL: (id: string) => `ai-model/${id}`,
    OAUTH_OPENROUTER: "ai-model/oauth/openrouter",
  },
  SESSION: {
    BY_CLIENT: (clientId: string) => `session/client/${clientId}`,
    DETAIL: (id: string) => `session/${id}`,
    SET_MODEL: (id: string) => `session/${id}/model`,
  },
  CONTEXT: {
    LIST: "context",
    DETAIL: (id: string) => `context/${id}`,
  },
  TASK: {
    LIST: "task",
    DETAIL: (id: string) => `task/${id}`,
    DONE: (id: string) => `task/${id}/done`,
    CANCEL: (id: string) => `task/${id}/cancel`,
  },
  APP: {
    LIST: "app",
    GOOGLE_AUTH_URL: "app/google/auth-url",
    GOOGLE_CONNECT: "app/google/connect",
    DISCONNECT: (id: string) => `app/${id}`,
  },
  CONTENT: {
    LIST: "content",
    DETAIL: (id: string) => `content/${id}`,
    GENERATE: "content/generate",
    APPROVE: (id: string) => `content/${id}/approve`,
    REJECT: (id: string) => `content/${id}/reject`,
    REVISE: (id: string) => `content/${id}/revise`,
    CAPTION: (id: string) => `content/${id}/caption`,
    ASSET: (id: string) => `content/${id}/asset`,
    ASSET_FROM_MEDIA: (id: string) => `content/${id}/asset-from-media`,
    PUBLISH: (id: string) => `content/${id}/publish`,
  },
  MEDIA: {
    LIST: "media",
    UPLOAD: "media",
    DELETE: (id: string) => `media/${id}`,
  },
  BOT: {
    STATUSES: "bot/statuses",
    STATUS: (id: string) => `bot/${id}/status`,
    START: (id: string) => `bot/${id}/start`,
    STOP: (id: string) => `bot/${id}/stop`,
    RESTART: (id: string) => `bot/${id}/restart`,
  },
} as const
